In [24]:
import numpy as np

In [61]:
z = np.random.default_rng(seed = 42)

In [62]:
y = z.normal(loc = 100, scale = 1, size = 50)

In [63]:
y

array([100.30471708,  98.96001589, 100.7504512 , 100.94056472,
        98.04896481,  98.69782049, 100.1278404 ,  99.68375741,
        99.98319884,  99.14695607, 100.87939797, 100.77779194,
       100.0660307 , 101.12724121, 100.46750934,  99.14070754,
       100.36875078,  99.0411174 , 100.8784503 ,  99.95007409,
        99.81513764,  99.31907046, 101.22254134,  99.84547052,
        99.57167218,  99.64786645, 100.53230919, 100.36544406,
       100.41273261, 100.430821  , 102.1416476 ,  99.59358498,
        99.48775727,  99.18622727, 100.61597942, 101.12897229,
        99.88605254,  99.15984352,  99.17551878, 100.65059279,
       100.74325417, 100.54315427,  99.33449029, 100.23216132,
       100.11668581, 100.2186886 , 100.87142878, 100.22359555,
       100.67891356, 100.06757907])

In [64]:
np.mean(y)

np.float64(100.09121103049301)

In [68]:
np.random.default_rng(seed=42)

Generator(PCG64) at 0x7FF175C290E0

In [80]:
rng = np.random.default_rng(3)


In [84]:
y = rng.standard_normal((10, 3))
print(y)

[[ 0.02425957  1.54582085  0.54510552]
 [-0.50522874 -0.18283897  0.54052513]
 [ 1.93508803 -0.26962033 -0.24355868]
 [ 1.0023136  -0.88645994 -0.29172023]
 [ 0.88253897  0.58035002  0.0915167 ]
 [ 0.67010435 -2.82816231  1.02130682]
 [-0.95964476 -1.66861984  0.27644576]
 [ 0.70054489 -0.44476746 -1.07640584]
 [ 0.02612483 -0.05274731  1.40559817]
 [ 0.74740799  0.19381565  1.11163321]]


In [90]:
y.mean(1)

array([ 0.70506198, -0.04918086,  0.47396968, -0.05862219,  0.51813523,
       -0.37891704, -0.78393961, -0.2735428 ,  0.45965856,  0.68428561])